"""The agent loop, written as an event generator.

Events stream to the UI over SSE (tool calls appear live, write operations
pause for human approval); the non-streaming wrapper `run_agent` consumes the
same generator for the plain /api/chat endpoint and the eval harness.
"""
import json
import os
from dataclasses import dataclass, field
from typing import Iterator

from groq import Groq

from .guardrails import APPROVALS, requires_approval
from .models import Endpoint, ToolCallTrace
from .router import select_endpoints
from .tools import build_toolset, execute_endpoint

AGENT_MODEL = os.environ.get("GROQ_AGENT_MODEL", "llama-3.3-70b-versatile")
MAX_ITERATIONS = 8

SYSTEM_PROMPT = """You are an API agent generated by Doc2Agent. You answer user
questions by calling the API tools you have been given — each tool is a real
endpoint of {base_url}, generated from its documentation.

Guidelines:
- Prefer calling tools over guessing. Chain calls when one endpoint's output
  feeds another (e.g. look up an ID first, then fetch details).
- NEVER invent or guess IDs. Only use exact IDs that appeared in a previous
  tool response. If a step needs an ID you don't have yet, make the call that
  returns it first and wait for the result.
- Write operations (POST/PUT/PATCH/DELETE) may require human approval. If a
  call is denied by the human, respect the denial — do not retry it; tell the
  user it was declined.
- If a call fails, read the error and retry with corrected parameters once.
- Only claim an action succeeded if the API actually returned success for it.
  If something failed, say exactly what failed.
- Answer concisely, cite concrete values from responses, and say which
  endpoints you used.
- If no tool can answer the question, say so honestly.

Available endpoints (a subset may be selected per question for large APIs):
{endpoint_summary}
"""


@dataclass
class AgentSession:
    base_url: str
    endpoints: list[Endpoint]
    api_key: str | None = None
    auth_header: str = "Authorization"
    auth_scheme: str = "Bearer"
    auto_approve: bool = False
    messages: list = field(default_factory=list)

    def __post_init__(self):
        if not self.messages:
            summary = "\n".join(
                f"- {ep.method} {ep.path}: {ep.description}" for ep in self.endpoints[:60]
            )
            if len(self.endpoints) > 60:
                summary += f"\n… and {len(self.endpoints) - 60} more"
            self.messages = [
                {
                    "role": "system",
                    "content": SYSTEM_PROMPT.format(
                        base_url=self.base_url, endpoint_summary=summary
                    ),
                }
            ]

    def to_dict(self) -> dict:
        return {
            "base_url": self.base_url,
            "endpoints": [ep.model_dump() for ep in self.endpoints],
            "api_key": self.api_key,
            "auth_header": self.auth_header,
            "auth_scheme": self.auth_scheme,
            "auto_approve": self.auto_approve,
            "messages": self.messages,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "AgentSession":
        return cls(
            base_url=data["base_url"],
            endpoints=[Endpoint.model_validate(e) for e in data["endpoints"]],
            api_key=data.get("api_key"),
            auth_header=data.get("auth_header", "Authorization"),
            auth_scheme=data.get("auth_scheme", "Bearer"),
            auto_approve=data.get("auto_approve", False),
            messages=data.get("messages") or [],
        )


def _execute(session: AgentSession, endpoint: Endpoint, args: dict):
    return execute_endpoint(
        endpoint, args, session.base_url,
        session.api_key, session.auth_header, session.auth_scheme,
    )


def run_agent_events(
    session: AgentSession, user_message: str, interactive: bool = False
) -> Iterator[dict]:
    """Yield event dicts: routing, tool_call, approval_required,
    approval_result, tool_result, reply."""
    client = Groq()
    session.messages.append({"role": "user", "content": user_message})

    selected, categories = select_endpoints(user_message, session.endpoints, client)
    if categories is not None:
        yield {"type": "routing", "categories": categories, "tool_count": len(selected)}
    tool_schemas, registry = build_toolset(selected)

    for _ in range(MAX_ITERATIONS):
        completion = client.chat.completions.create(
            model=AGENT_MODEL,
            messages=session.messages,
            tools=tool_schemas,
            tool_choice="auto",
            parallel_tool_calls=False,  # dependent calls need each result first
            temperature=0.2,
        )
        message = completion.choices[0].message

        if not message.tool_calls:
            reply = message.content or "(no response)"
            session.messages.append({"role": "assistant", "content": reply})
            yield {"type": "reply", "text": reply}
            return

        session.messages.append(
            {
                "role": "assistant",
                "content": message.content,
                "tool_calls": [
                    {
                        "id": tc.id,
                        "type": "function",
                        "function": {
                            "name": tc.function.name,
                            "arguments": tc.function.arguments,
                        },
                    }
                    for tc in message.tool_calls
                ],
            }
        )

        for tc in message.tool_calls:
            endpoint = registry.get(tc.function.name)
            try:
                args = json.loads(tc.function.arguments or "{}")
            except json.JSONDecodeError:
                args = {}
            if not isinstance(args, dict):
                args = {}

            if endpoint is None:
                result = json.dumps({"error": f"Unknown tool {tc.function.name}"})
                trace = ToolCallTrace(
                    tool=tc.function.name, method="?", url="?", ok=False,
                    summary="unknown tool",
                )
                yield {"type": "tool_result", "trace": trace.model_dump()}
                session.messages.append(
                    {"role": "tool", "tool_call_id": tc.id, "content": result}
                )
                continue

            yield {
                "type": "tool_call",
                "tool": tc.function.name,
                "method": endpoint.method,
                "path": endpoint.path,
                "args": args,
            }

            approved = True
            if requires_approval(endpoint) and not session.auto_approve:
                if not interactive:
                    approved = False
                    denial = (
                        "Denied by policy: this is a write operation and human "
                        "approval is required. Ask the user to approve it in the "
                        "interactive UI or enable auto-approve."
                    )
                else:
                    approval_id = APPROVALS.create(
                        {"method": endpoint.method, "path": endpoint.path, "args": args}
                    )
                    yield {
                        "type": "approval_required",
                        "approval_id": approval_id,
                        "method": endpoint.method,
                        "path": endpoint.path,
                        "args": args,
                    }
                    approved = APPROVALS.wait(approval_id)
                    yield {"type": "approval_result", "approved": approved}
                    denial = "Denied by the human operator. Do not retry this call."

            if approved:
                result, trace = _execute(session, endpoint, args)
                trace.tool = tc.function.name
            else:
                result = json.dumps({"error": denial})
                trace = ToolCallTrace(
                    tool=tc.function.name, method=endpoint.method,
                    url=session.base_url.rstrip("/") + endpoint.path,
                    ok=False, summary="✋ denied — human approval not given",
                )

            yield {"type": "tool_result", "trace": trace.model_dump()}
            session.messages.append(
                {"role": "tool", "tool_call_id": tc.id, "content": result}
            )

    # Round limit reached: force a final text answer (no tools) so the user
    # gets an honest account of what succeeded and what didn't.
    session.messages.append(
        {
            "role": "user",
            "content": (
                "You have reached the tool-call limit. Based only on the tool "
                "results above, tell the user what succeeded, what failed and why. "
                "Do not claim anything succeeded unless a call returned success."
            ),
        }
    )
    completion = client.chat.completions.create(
        model=AGENT_MODEL, messages=session.messages, temperature=0.2
    )
    reply = completion.choices[0].message.content or "(no response)"
    session.messages.append({"role": "assistant", "content": reply})
    yield {"type": "reply", "text": reply}


def run_agent(session: AgentSession, user_message: str) -> tuple[str, list[ToolCallTrace]]:
    """Non-streaming wrapper over the same event generator."""
    reply, traces = "", []
    for event in run_agent_events(session, user_message, interactive=False):
        if event["type"] == "tool_result":
            traces.append(ToolCallTrace.model_validate(event["trace"]))
        elif event["type"] == "reply":
            reply = event["text"]
    return reply, traces
