"""Export an ingested API as a standalone MCP (Model Context Protocol) server.

Generates a single runnable Python file exposing every extracted endpoint as
an MCP tool, so the agent Doc2Agent synthesized becomes usable from Claude
Desktop, Cursor, or any MCP client. The generated file depends only on
`mcp` and `httpx`.
"""
import json
import keyword
import re

from .models import Endpoint
from .tools import MAX_TOOLS

TYPE_MAP = {"integer": "int", "number": "float", "boolean": "bool"}
DEFAULTS = {"int": "0", "float": "0.0", "bool": "False", "str": '""'}

HEADER_TEMPLATE = '''"""MCP server for {title}
Generated by Doc2Agent from the API's documentation.

Run:
    pip install "mcp[cli]" httpx
    python {filename}

Claude Desktop config (claude_desktop_config.json):
    {{"mcpServers": {{"{name}": {{"command": "python", "args": ["<absolute path to this file>"]}}}}}}

Set API_KEY (and optionally AUTH_HEADER / AUTH_SCHEME) in the environment if
the API needs authentication.
"""
import json
import os

import httpx
from mcp.server.fastmcp import FastMCP

BASE_URL = {base_url!r}
mcp = FastMCP({name!r})


def _request(method: str, path: str, locations: dict, values: dict) -> str:
    query, body, headers = {{}}, {{}}, {{"Accept": "application/json"}}
    api_key = os.environ.get("API_KEY", "")
    if api_key:
        header = os.environ.get("AUTH_HEADER", "Authorization")
        scheme = os.environ.get("AUTH_SCHEME", "Bearer")
        headers[header] = f"{{scheme}} {{api_key}}".strip() if header == "Authorization" else api_key
    for arg, (original, location) in locations.items():
        value = values.get(arg)
        if value in (None, "", 0, 0.0, False) and not isinstance(value, bool):
            continue
        if location == "path":
            path = path.replace("{{" + original + "}}", str(value))
        elif location == "body":
            body[original] = value
        elif location == "header":
            headers[original] = str(value)
        else:
            query[original] = value
    resp = httpx.request(
        method, BASE_URL.rstrip("/") + "/" + path.lstrip("/"),
        params=query or None, json=body or None, headers=headers,
        timeout=25, follow_redirects=True,
    )
    return json.dumps({{"status": resp.status_code, "body": resp.text[:8000]}})

'''

FOOTER = '''

if __name__ == "__main__":
    mcp.run()
'''


def _py_ident(name: str, used: set) -> str:
    ident = re.sub(r"[^a-zA-Z0-9_]", "_", name) or "arg"
    if ident[0].isdigit():
        ident = "p_" + ident
    if keyword.iskeyword(ident):
        ident += "_"
    base, n = ident, 2
    while ident in used:
        ident, n = f"{base}_{n}", n + 1
    used.add(ident)
    return ident


def _fn_name(endpoint: Endpoint, index: int, used: set) -> str:
    slug = re.sub(r"[^a-zA-Z0-9_]+", "_", endpoint.path).strip("_") or "root"
    name = f"{endpoint.method.lower()}_{slug}"[:50]
    if keyword.iskeyword(name) or name in used:
        name = f"{name}_{index}"
    used.add(name)
    return name


def generate_mcp_server(base_url: str, endpoints: list[Endpoint], title: str) -> str:
    name = re.sub(r"[^a-zA-Z0-9_-]+", "-", title.lower()).strip("-") or "doc2agent-api"
    filename = f"{name.replace('-', '_')}_mcp.py"
    parts = [
        HEADER_TEMPLATE.format(title=title, filename=filename, name=name, base_url=base_url)
    ]
    used_fn_names: set = set()

    for i, ep in enumerate(endpoints[:MAX_TOOLS]):
        fn = _fn_name(ep, i, used_fn_names)
        used_args: set = set()
        sig_required, sig_optional, locations, param_doc_lines = [], [], {}, []
        for p in ep.params:
            arg = _py_ident(p.name, used_args)
            py_type = TYPE_MAP.get(p.type, "str")
            locations[arg] = (p.name, p.location)
            if p.required:
                sig_required.append(f"{arg}: {py_type}")
            else:
                sig_optional.append(f"{arg}: {py_type} = {DEFAULTS[py_type]}")
            if p.description:
                param_doc_lines.append(f"        {arg}: ({p.location}) {p.description}")
        sig = ", ".join(sig_required + sig_optional)

        doc = f"{ep.method} {ep.path}"
        if ep.description:
            doc += f" — {ep.description}"
        docstring = doc + ("\n\n    Args:\n" + "\n".join(param_doc_lines) if param_doc_lines else "")

        parts.append(
            f'@mcp.tool()\n'
            f'def {fn}({sig}) -> str:\n'
            f'    """{docstring}"""\n'
            f'    return _request({ep.method!r}, {ep.path!r}, {json.dumps(locations)}, locals())\n\n'
        )

    parts.append(FOOTER)
    return "".join(parts)
